name: Check black coding style

on:
  push:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: '3.11'
      - name: Black Check
        uses: psf/black@22.8.0
