name: Build the documentation

on:
  push:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt install pandoc
          pip3 install -r requirements.txt
          pip install .
          pip3 install h5py --upgrade --no-dependencies
          pip3 install cached-property
      - name: Build documentation
        run: |
          cd docs
          make html
