name: Build the documentation

on:
  push:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        env: 
          super_secret: ${{ secrets.PAPYRUS_ACCESS }}
        run: |
          sudo apt install pandoc
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install .

      - name: Build documentation
        run: |
          cd docs
          make html
